Empty parents for genesis events
Fantom-foundation/Sonic pull request #227
Opened 2024-10-15 08:27 UTC by Tjofil

This PR makes all genesis events not have any parents. Having a parent by other creator as a genesis turns out to be problematic due to Lachesis' iterative frame calculation, thus inducing frame non-monotonicity for the event chains. Such non-monotonicity makes future incrementalization efforts impossible and potentially hides other performance and security concerns.

We also introduce a new flag used only for `events import` subcommand that instructs Lachesis to suppress the frame check panic. This may be useful for regression testing where the monotonicity fix from https://github.com/Fantom-foundation/lachesis-base-sonic/pull/3 is not important and could obstruct ingestion of historical data.

2024-10-15 08:30 UTC, psubotic approved these changes

2024-10-15 09:08 UTC, psubotic commented
document describing change: https://docs.google.com/document/d/1yIcoJooH4LQnsfd4Z670mfQPYl3R2XPOrbuNp6cq9Ug/edit?usp=sharing

2024-10-15 10:22 UTC, psubotic submitted a review, later dismissed

2024-10-21 07:22 UTC, HerbertJordan requested changes
This PR covers two features:
 - the change making sure that every genesis event is free of any parent event link
 - the introduction of the `SuppressFramePanicFlag`

These changes are independent of each other and should be handled in two distinct PRs. Would you be fine splitting this PR up in two?

2024-10-21 07:22 UTC, HerbertJordan commented on gossip/emitter/emitter_test.go
> +	})
This is a rather unexpected location for a test that targets a function implemented in `parents.go`. By the usual convention, it should be placed in a file named `parents_test.go`.

The test also seems to be rather unrelated to any other test in this file, so factoring it out should be rather straight forward.

2024-10-21 07:22 UTC, HerbertJordan commented on gossip/emitter/emitter_test.go
> +		Return(hash.Events{(&tdag.TestEvent{}).ID(), (&tdag.TestEvent{}).ID()}).
nit: no need to specify a return value if this function is supposed to never be called (`Times(0)`)

2024-10-21 07:22 UTC, HerbertJordan commented on config/flags/flags.go
> +		Name:  "suppress-frame-panic",
It looks like the convention in this list of flags is to use a naming schema like `<component>.<property>` to group flags. The property is all-lower-case without spaces. According to this, this flag should be named something like `lachesis.suppressframepanic` or `lachesis.ignoreframemissmatch`. Due to the long name I would probably take `lachesis.ignore-frame-miss-match`.
Wdyt?

2024-10-21 08:29 UTC, Tjofil commented
> This PR covers two features:
> 
> * the change making sure that every genesis event is free of any parent event link
> * the introduction of the `SuppressFramePanicFlag`
> 
> These changes are independent of each other and should be handled in two distinct PRs. Would you be fine splitting this PR up in two?

We planned with the testing team to do it more quickly, in one go. The suppression flag is needed both because of this PR and https://github.com/Fantom-foundation/lachesis-base-sonic/pull/3, i.e. the suppression flag is a direct consequence of all the monotonicity fixing effort.

I can still make it two PRs if you prefer.

2024-10-21 08:39 UTC, HerbertJordan commented
> We planned with the testing team to do it more quickly, in one go. The suppression flag is needed both because of this PR and [Fantom-foundation/lachesis-base-sonic#3](https://github.com/Fantom-foundation/lachesis-base-sonic/pull/3), i.e. the suppression flag is a direct consequence of all the monotonicity fixing effort.
> 
> I can still make it two PRs if you prefer.

Typically, PRs should be focused on a single change. I think it would not hurt to split those up, and it should not take more than 10 minutes. I can review them quickly as they become available.

However, if keeping those two changes bundled up is fixing some integration test issue for you, its fine for me to keep it as it is.

2024-10-21 10:47 UTC, closed without merging