Add end-to-end BlobBaseFee instruction test
Fantom-foundation/Sonic pull request #255
Opened 2024-10-23 13:53 UTC by facuMH

This PR adds an end-to-end test for BlobBaseFee opcode ([EIP-7516](https://eips.ethereum.org/EIPS/eip-7516))

The test added performs the following steps:
- deploys a smart contract capable of retrieving the current blobbasefee for archive queries
- fetches the blobbasefeefrom the contract using a transaction (via a log message)
- fetches the blobbasefee from the archive using another method of the contract
- checks that the blobbasefee is zero and all sources report the same value. We compare to zero because BlobBaseFee is currently not supported by go-ethereum-sonic

2024-10-24 07:24 UTC, HerbertJordan requested changes
Looks good, but I have an additional feature request.

2024-10-24 07:24 UTC, HerbertJordan commented on tests/blobbasefee_test.go
Studying EIP-7516 it actually lists a method how to extract the blob-base-fee from a block header in its [Specification](https://eips.ethereum.org/EIPS/eip-7516#specification) section. It cites the formula for computing the blob-base-fee in [EIP-4844](https://eips.ethereum.org/EIPS/eip-4844#gas-accounting). This formula depends on [these](https://github.com/Fantom-foundation/go-ethereum-sonic/blob/2400937cc3b1c370ea8735d7af86eac621e4eb70/core/types/block.go#L89-L93) two fields in the block header.

Can you implement this formula in the test and verify that the header information is consistent with the blob basefee reported in transactions and archive queries?

2024-10-25 10:35 UTC, HerbertJordan submitted a review, later dismissed
Looks good, thanks!

2024-10-25 10:54 UTC, jenikd commented
Once PR https://github.com/Fantom-foundation/Sonic/pull/261 is merged, also comparison to the RPC function can be added, something like this:
```
	// call the blob base fee rpc method
	fromRpc := new(hexutil.Uint64)
	err = client.Client().Call(&fromRpc, "eth_blobBaseFee")
	if err != nil {
		t.Fatalf("failed to get blob base fee from rpc; %v", err)
	}
```

2024-10-25 10:54 UTC, jenikd submitted a review, later dismissed

2024-10-25 13:39 UTC, jenikd approved these changes
Thanks

2024-10-28 08:04 UTC, HerbertJordan approved these changes

2024-10-28 08:04 UTC, HerbertJordan commented on tests/blobbasefee_test.go
> +	// we check blob base fee is zero because it is not implemented yet. TODO issue #147
This comment is out-dated.

2024-10-28 09:58 UTC, HerbertJordan approved these changes

2024-10-28 10:02 UTC, merged