Introduce getAccount rpc method
Fantom-foundation/Sonic pull request #317
Opened 2024-11-18 12:15 UTC by cabrador

This PR adds `getAccount` method to the RPC according to [this](https://www.quicknode.com/docs/ethereum/eth_getAccount) documentation.

**Note:** As written in the code [here](https://github.com/Fantom-foundation/Sonic/blob/2001b3718c9182b159897adc0ceb66ba608dcb47/gossip/evmstore/carmen.go#L162) - Carmen currently actually does support `GetStorageRoot(addr)` - it returns a const non-empty hash for accounts which do not have empty storage and an empty hash for account which do have empty storage.

2024-11-19 10:37 UTC, jenikd commented on tests/get_account_test.go
> +		t.Errorf("accounts nonce is expected to by at least 1")
```suggestion
		t.Errorf("account nonce is expected to by at least 1")
```

2024-11-19 12:33 UTC, jenikd approved these changes
Thanks

2024-11-19 16:51 UTC, HerbertJordan requested changes
I agree with @jmpike, unless we provide a correct storage root, we should not offer this API endpoint.

2024-11-20 07:54 UTC, cabrador commented
I agree with you. Im closing this PR. We can re-open it once Carmen implements `GetStorageRoot` correctly.

2024-11-20 07:54 UTC, closed without merging