Refactor defer-close with error handling
Fantom-foundation/Sonic pull request #378
Opened 2024-12-16 15:14 UTC by facuMH

This PR contributes to https://github.com/Fantom-foundation/sonic-admin/issues/90

This PR adds real life use cases of both functions provided the caution package to properly handler errors in case of `defer` and `close`. 

This PR fixes some of the unhandled errors reported by the external audit. Most (if not all) of them are from either `defer close` patterns or similar cleanups or unhandled close errors.

Test list to verify we don't have double closes or any new errors that were previously ignored and now crash:
- [x] run `make test`
- [ ] aida test
- [ ] testing suggestions ?

2024-12-17 15:51 UTC, facuMH commented on cmd/sonictool/app/heal.go
> +		defer caution.CloseAndReportError(&err, writer, "failed to close writer")
```suggestion
		defer caution.CloseAndReportError(&exportErr, writer, "failed to close writer")
```

2024-12-17 15:54 UTC, facuMH commented on cmd/sonictool/genesis/signature.go
> +	err = fmt.Errorf("failed to flush genesis file: %w", err)
this assignment needs to be inside an if, flush could return nil.

2024-12-18 09:37 UTC, LuisPH3 requested changes
I saw some details that need handing;

Additionally, I would like to avoid using `caution.CloseAndReportError` for scenarios without `defer`, it does nonstandard error handling, and it may be a little convoluted to read. We can talk about a replacement.

2024-12-18 14:59 UTC, LuisPH3 approved these changes

2025-01-14 11:26 UTC, HerbertJordan requested changes
I do not really like that most of this refactoring is introducing named return values for non-trivial functions. It makes functions harder to read, and without an IDE highlighting it is difficult to verify that a return value name is not shadowed in a nested scope.

But I do understand that this seems to be a requirement imposed by the `caution` package, and alternatives might be even more cumbersome.

However, I would like to ask to reconsider the naming and placement of the function `IfErrorAddContext` as addressed in the comments. Please have a look.

2025-01-14 11:26 UTC, HerbertJordan commented on cmd/sonictool/app/sign_genesis.go
> +func getGenesisHeaderHashes(genesisFile string) (header ogenesis.Header, genesisHashes ogenesis.Hashes, err error) {
nit: Using named return values makes functions more complicated to read -- and this one in particular. Consider rewriting this into a version not using named return values.

2025-01-14 11:26 UTC, HerbertJordan commented on tests/integration_test_net.go
> +		fmt.Print("failed to close listener:", err)
nit: panic instead?

2025-01-14 11:26 UTC, HerbertJordan commented on utils/errlock/errlock.go
> +		return fmt.Errorf("Node isn't allowed to start due to an error reading lock file. Please fix the issue and then delete file \"%s\". Error message:\n%w", eLockPath, err)
please check: The message, I guess, should be updated as follows:
```suggestion
		return fmt.Errorf("Node isn't allowed to start due to an error reading the lock file "%s". Please fix the issue. Error message:\n%w", eLockPath, err)
```

2025-01-14 14:01 UTC, facuMH commented on tests/integration_test_net.go
> +		fmt.Print("failed to close listener:", err)
I was trying to handler errors without modifying the current behaviour, in that regard, a log or print seemed a better approach than panicking, which could lead to an unexpected runtime panic in a non critical situation.

2025-01-15 09:30 UTC, HerbertJordan commented on tests/integration_test_net.go
> +		fmt.Print("failed to close listener:", err)
This is test infrastructure - nobody will read the log unless the test fails or crashes.

2025-01-15 09:54 UTC, facuMH commented on cmd/sonicd/app/launcher.go
> +		return caution.IfErrorAddContext(prompt.Stdin.Close(), "failed to reset terminal input")
I will go for `AnnotateIfError`

2025-01-15 09:54 UTC, facuMH commented on utils/caution/caution.go
> +func IfErrorAddContext(err error, message string) error {
moving it to it's own file in utils

2025-01-15 13:52 UTC, facuMH commented on cmd/sonictool/app/sign_genesis.go
> +func getGenesisHeaderHashes(genesisFile string) (header ogenesis.Header, genesisHashes ogenesis.Hashes, err error) {
added return values to each return.

2025-01-15 16:36 UTC, HerbertJordan approved these changes

2025-01-15 16:36 UTC, HerbertJordan commented on cmd/sonictool/genesis/signature.go
> +	utils.AnnotateIfError(err, "failed to flush genesis file:")
this should be
```suggestion
	return utils.AnnotateIfError(err, "failed to flush genesis file:")
```

Would an unhandled error produced by `AnnotateIfError` like in this case be detected by static linters?

2025-01-15 16:36 UTC, HerbertJordan commented on utils/annotateError_test.go
> +	require.ErrorContains(t, errWithContext, "message: someError")
nit: it should also check that `errors.Is(errWithContext, err)` is true.

2025-01-16 08:14 UTC, facuMH commented on cmd/sonictool/genesis/signature.go
> +	utils.AnnotateIfError(err, "failed to flush genesis file:")
yes it does get detected.

2025-01-16 12:54 UTC, LuisPH3 commented on cmd/sonicd/app/launcher.go
> +		caution.CloseAndReportError(&err, prompt.Stdin, "failed to reset terminal input")
this case is not defered, close can be called using normal procedures.

2025-01-16 12:54 UTC, LuisPH3 commented on topicsdb/search_parallel.go
> +		log.Warn("searchParallel", "err", err)
since the first time i saw this line, i dont really know what to do with it. 
The search algorithm will look for something not returning an error and producing errors may be the intended use. 

The context we add to warn is not good.
- Write a complete sentence in warn:  "error produced during parallel search"
- Add a comment explaining the issue, so that  the problem is understood in case this line turns too verbose (which could affect performance of some hot region)

@HerbertJordan @kjezek do you know what this code is about?

2025-01-16 12:54 UTC, LuisPH3 commented on integration/assembly.go
>  		if err != nil {
```
//	}
func ExecuteAndReportError(err *error, f func() error, message string) {
	fErr := f()
	if fErr != nil {
		*err = errors.Join(*err, fmt.Errorf("%s: %w", message, fErr))
	}
}
```

this if is superfluous.

2025-01-17 16:04 UTC, HerbertJordan approved these changes

2025-01-17 16:04 UTC, HerbertJordan commented on topicsdb/search_parallel.go
> +		log.Warn("searchParallel", "err", err)
This code is the implementation of the log-filter feature. You can send RPC queries to the service asking for log messages listing a given set of topics. This function is searching for those and does a call-back on `onMatched` for each element and, as it looks like, a final one passing a `nil` to indicate that all matches have been reported and that there are no more.

The only time this function is actually used is in line 94 above, where `onMatched` returns an error if, for instance, the execution context is canceled. Another option is that the consumer of the match failed to consume it, which seems to be ignored, as shown in line 116.

I guess the best option here, matching the action in line 116, is to simply ignore the error.

2025-02-03 13:08 UTC, LuisPH3 commented
Please, Add one deferred error missing : `gossip/handler.go:700:19:       defer msg.Discard()`

2025-02-06 12:02 UTC, facuMH commented
moved to https://github.com/0xsoniclabs/sonic/pull/7

2025-02-06 12:02 UTC, closed without merging